// Generated by strings/generate.py from strings/strings.json — edit those, not this file.

import Foundation

/// Interface languages: code and native name, in table order.
enum Lang {
    static let codes = ["en", "ru", "de", "es", "fr"]
    static let names = ["English", "Русский", "Deutsch", "Español", "Français"]

    /// The language in use: the one chosen in settings, else the system's, else English.
    static var index: Int {
        let chosen = UserDefaults.standard.string(forKey: "language") ?? ""
        if let i = codes.firstIndex(of: chosen) { return i }
        for preferred in Locale.preferredLanguages {
            if let i = codes.firstIndex(of: String(preferred.prefix(2))) { return i }
        }
        return 0
    }

    /// Words that start a question in any interface language.
    static let questionWords: Set<String> = [
        "what", "how", "why", "when", "where", "who", "which", "explain", "write", "translate", "can", "is", "are", "should", "does", "do", "что", "как", "почему", "зачем", "когда", "где", "кто", "сколько", "какой", "какая", "какие", "какое", "можно", "объясни", "напиши", "переведи", "посчитай", "расскажи", "придумай", "сравни", "чем", "was", "wie", "warum", "wann", "wo", "wer", "welche", "welcher", "erkläre", "schreibe", "übersetze", "kann", "ist", "sind", "qué", "que", "cómo", "como", "por", "cuándo", "dónde", "quién", "cuál", "explica", "escribe", "traduce", "puedo", "es", "quoi", "que", "comment", "pourquoi", "quand", "où", "qui", "quel", "quelle", "explique", "écris", "traduis", "peut", "est"
    ]
}

private let table: [String: [String]] = [
    "search_placeholder": ["Search or ask a question", "Поиск или вопрос", "Suchen oder fragen", "Buscar o preguntar", "Rechercher ou poser une question"],
    "followup_placeholder": ["Ask a follow-up…", "Задайте уточняющий вопрос…", "Rückfrage stellen…", "Haz una pregunta de seguimiento…", "Posez une question de suivi…"],
    "ask_row": ["Ask {0}", "Спросить {0}", "{0} fragen", "Preguntar a {0}", "Demander à {0}"],
    "application": ["Application", "Программа", "Programm", "Aplicación", "Application"],
    "thinking": ["Thinking…", "Думает…", "Denkt nach…", "Pensando…", "Réflexion…"],
    "hint_stop": ["esc — stop", "esc — остановить", "esc — anhalten", "esc — detener", "esc — arrêter"],
    "hint_done": ["↩ follow up · retry   {0} copy answer   esc back", "↩ уточнить · повторить   {0} копировать ответ   esc назад", "↩ nachfragen · wiederholen   {0} Antwort kopieren   esc zurück", "↩ seguir · reintentar   {0} copiar respuesta   esc atrás", "↩ relancer · réessayer   {0} copier la réponse   esc retour"],
    "welcome_subtitle": ["Search your computer and ask AI in one bar", "Поиск по компьютеру и ответы ИИ в одной строке", "Computer durchsuchen und KI fragen in einer Leiste", "Busca en tu ordenador y pregunta a la IA en una barra", "Cherchez sur votre ordinateur et interrogez l'IA dans une barre"],
    "hotkey_hint": ["— open the bar from anywhere", "— открыть строку из любого места", "— Leiste überall öffnen", "— abrir la barra desde cualquier lugar", "— ouvrir la barre depuis n'importe où"],
    "auth_checking": ["Checking Claude…", "Проверяю Claude…", "Claude wird geprüft…", "Comprobando Claude…", "Vérification de Claude…"],
    "auth_ok": ["Claude connected", "Claude подключён", "Claude verbunden", "Claude conectado", "Claude connecté"],
    "auth_signed_out": ["Claude: sign-in needed", "Claude: нужен вход", "Claude: Anmeldung nötig", "Claude: inicia sesión", "Claude : connexion requise"],
    "auth_missing": ["Claude Code is not installed", "Claude Code не установлен", "Claude Code ist nicht installiert", "Claude Code no está instalado", "Claude Code n'est pas installé"],
    "sign_in": ["Sign in", "Войти", "Anmelden", "Iniciar sesión", "Se connecter"],
    "download": ["Download", "Скачать", "Herunterladen", "Descargar", "Télécharger"],
    "model": ["Model", "Модель", "Modell", "Modelo", "Modèle"],
    "language": ["Language", "Язык", "Sprache", "Idioma", "Langue"],
    "language_system": ["System", "Как в системе", "System", "Sistema", "Système"],
    "connect_model": ["Connect a model…", "Подключить модель…", "Modell verbinden…", "Conectar un modelo…", "Connecter un modèle…"],
    "delete_connection": ["Remove connection", "Удалить подключение", "Verbindung entfernen", "Eliminar conexión", "Supprimer la connexion"],
    "launch_at_login": ["Open at login", "Запускать при входе в систему", "Beim Anmelden öffnen", "Abrir al iniciar sesión", "Ouvrir à la connexion"],
    "show_on_launch": ["Show this window on launch", "Показывать это окно при запуске", "Dieses Fenster beim Start zeigen", "Mostrar esta ventana al abrir", "Afficher cette fenêtre au démarrage"],
    "open_search": ["Open search", "Открыть поиск", "Suche öffnen", "Abrir búsqueda", "Ouvrir la recherche"],
    "menu_open_search": ["Open search  ({0})", "Открыть поиск  ({0})", "Suche öffnen  ({0})", "Abrir búsqueda  ({0})", "Ouvrir la recherche  ({0})"],
    "menu_window": ["ClaudeLight window…", "Окно ClaudeLight…", "ClaudeLight-Fenster…", "Ventana de ClaudeLight…", "Fenêtre ClaudeLight…"],
    "menu_launch_at_login": ["Open at login", "Запускать при входе", "Beim Anmelden öffnen", "Abrir al iniciar sesión", "Ouvrir à la connexion"],
    "menu_quit": ["Quit", "Выйти", "Beenden", "Salir", "Quitter"],
    "model_auto": ["Auto", "Авто", "Auto", "Auto", "Auto"],
    "note_auto": ["as in Claude Code", "как в Claude Code", "wie in Claude Code", "como en Claude Code", "comme dans Claude Code"],
    "note_haiku": ["fastest", "самый быстрый", "am schnellsten", "el más rápido", "le plus rapide"],
    "note_sonnet": ["fast and smart", "быстрый и умный", "schnell und klug", "rápido e inteligente", "rapide et intelligent"],
    "note_opus": ["smartest", "самый умный", "am klügsten", "el más inteligente", "le plus intelligent"],
    "note_fable": ["needs credits", "нужны кредиты", "braucht Guthaben", "requiere créditos", "nécessite des crédits"],
    "connections": ["Connections", "Подключения", "Verbindungen", "Conexiones", "Connexions"],
    "form_title": ["Connect a model", "Подключить модель", "Modell verbinden", "Conectar un modelo", "Connecter un modèle"],
    "form_subtitle": ["Any service with an OpenAI-compatible API: address, model and key.", "Любой сервис с OpenAI-совместимым API: адрес, модель и ключ.", "Jeder Dienst mit OpenAI-kompatibler API: Adresse, Modell und Schlüssel.", "Cualquier servicio con API compatible con OpenAI: dirección, modelo y clave.", "Tout service avec une API compatible OpenAI : adresse, modèle et clé."],
    "service": ["Service", "Сервис", "Dienst", "Servicio", "Service"],
    "name": ["Name", "Название", "Name", "Nombre", "Nom"],
    "address": ["Address", "Адрес", "Adresse", "Dirección", "Adresse"],
    "api_key": ["API key", "API-ключ", "API-Schlüssel", "Clave API", "Clé API"],
    "key_stored": ["stored securely", "хранится в защищённом хранилище", "wird sicher gespeichert", "se guarda de forma segura", "stockée de façon sécurisée"],
    "key_not_needed": ["not needed", "не нужен", "nicht nötig", "no es necesaria", "inutile"],
    "cancel": ["Cancel", "Отмена", "Abbrechen", "Cancelar", "Annuler"],
    "connect": ["Connect", "Подключить", "Verbinden", "Conectar", "Connecter"],
    "preset_ollama": ["Ollama (this computer)", "Ollama (на этом компьютере)", "Ollama (dieser Computer)", "Ollama (este ordenador)", "Ollama (cet ordinateur)"],
    "preset_lmstudio": ["LM Studio (this computer)", "LM Studio (на этом компьютере)", "LM Studio (dieser Computer)", "LM Studio (este ordenador)", "LM Studio (cet ordinateur)"],
    "preset_other": ["Other address", "Другой адрес", "Andere Adresse", "Otra dirección", "Autre adresse"],
    "hint_example": ["e.g. {0}", "например, {0}", "z. B. {0}", "p. ej., {0}", "p. ex. {0}"],
    "hint_loaded_model": ["name of the loaded model", "имя загруженной модели", "Name des geladenen Modells", "nombre del modelo cargado", "nom du modèle chargé"],
    "hint_model_name": ["model name", "имя модели", "Modellname", "nombre del modelo", "nom du modèle"],
    "err_no_claude": ["Claude Code not found. Pick another model at the top right, or install Claude Code: https://claude.com/claude-code", "Claude Code не найден. Выберите другую модель справа вверху или установите Claude Code: https://claude.com/claude-code", "Claude Code nicht gefunden. Wählen Sie oben rechts ein anderes Modell oder installieren Sie Claude Code: https://claude.com/claude-code", "No se encontró Claude Code. Elige otro modelo arriba a la derecha o instala Claude Code: https://claude.com/claude-code", "Claude Code introuvable. Choisissez un autre modèle en haut à droite ou installez Claude Code : https://claude.com/claude-code"],
    "err_not_logged_in": ["Claude is not signed in. Press “Sign in” in the ClaudeLight window, or run `claude` and then `/login`.", "Claude не залогинен. Нажмите «Войти» в окне ClaudeLight или выполните `claude`, затем `/login`.", "Claude ist nicht angemeldet. Klicken Sie im ClaudeLight-Fenster auf „Anmelden“ oder führen Sie `claude` und dann `/login` aus.", "Claude no ha iniciado sesión. Pulsa «Iniciar sesión» en la ventana de ClaudeLight o ejecuta `claude` y luego `/login`.", "Claude n'est pas connecté. Cliquez sur « Se connecter » dans la fenêtre ClaudeLight ou lancez `claude` puis `/login`."],
    "err_start": ["Couldn't start claude: {0}", "Не удалось запустить claude: {0}", "claude konnte nicht starten: {0}", "No se pudo iniciar claude: {0}", "Impossible de lancer claude : {0}"],
    "err_claude": ["Claude returned an error.", "Claude вернул ошибку.", "Claude hat einen Fehler gemeldet.", "Claude devolvió un error.", "Claude a renvoyé une erreur."],
    "err_bad_url": ["The address of “{0}” is invalid.", "Неверный адрес подключения «{0}».", "Die Adresse von „{0}“ ist ungültig.", "La dirección de «{0}» no es válida.", "L'adresse de « {0} » est invalide."],
    "err_key": ["“{0}” rejected the key ({1}). Check the API key. {2}", "«{0}» не принял ключ ({1}). Проверьте API-ключ. {2}", "„{0}“ hat den Schlüssel abgelehnt ({1}). Prüfen Sie den API-Schlüssel. {2}", "«{0}» rechazó la clave ({1}). Revisa la clave API. {2}", "« {0} » a refusé la clé ({1}). Vérifiez la clé API. {2}"],
    "err_404": ["“{0}”: model or address not found (404). {1}", "«{0}»: модель или адрес не найдены (404). {1}", "„{0}“: Modell oder Adresse nicht gefunden (404). {1}", "«{0}»: modelo o dirección no encontrados (404). {1}", "« {0} » : modèle ou adresse introuvable (404). {1}"],
    "err_429": ["“{0}”: rate limit reached or out of funds (429). {1}", "«{0}»: превышен лимит запросов или закончились средства (429). {1}", "„{0}“: Ratenlimit erreicht oder kein Guthaben (429). {1}", "«{0}»: límite de peticiones o sin saldo (429). {1}", "« {0} » : limite atteinte ou crédit épuisé (429). {1}"],
    "err_status": ["“{0}” returned error {1}. {2}", "«{0}» вернул ошибку {1}. {2}", "„{0}“ meldete Fehler {1}. {2}", "«{0}» devolvió el error {1}. {2}", "« {0} » a renvoyé l'erreur {1}. {2}"],
    "err_connect": ["Couldn't reach “{0}”: {1}.", "Не удалось связаться с «{0}»: {1}.", "„{0}“ nicht erreichbar: {1}.", "No se pudo conectar con «{0}»: {1}.", "Impossible de joindre « {0} » : {1}."],
    "err_local_hint": [" Is the model server running on this computer?", " Запущен ли сервер модели на этом компьютере?", " Läuft der Modellserver auf diesem Computer?", " ¿Está el servidor del modelo en marcha en este ordenador?", " Le serveur du modèle tourne-t-il sur cet ordinateur ?"],
    "login_done": ["Done — you can close this window.", "Готово — можно закрыть это окно.", "Fertig — Sie können dieses Fenster schließen.", "Listo — puedes cerrar esta ventana.", "Terminé — vous pouvez fermer cette fenêtre."],
    "ask_chatgpt": ["Ask in ChatGPT", "Спросить в ChatGPT", "In ChatGPT fragen", "Preguntar en ChatGPT", "Demander dans ChatGPT"],
    "chatgpt_note": ["opens chatgpt.com with your subscription", "откроется chatgpt.com с вашей подпиской", "öffnet chatgpt.com mit Ihrem Abo", "abre chatgpt.com con tu suscripción", "ouvre chatgpt.com avec votre abonnement"],
    "show_chatgpt": ["Show “Ask in ChatGPT”", "Показывать «Спросить в ChatGPT»", "„In ChatGPT fragen“ zeigen", "Mostrar «Preguntar en ChatGPT»", "Afficher « Demander dans ChatGPT »"],
    "err_stream": ["“{0}” stopped answering: {1}", "«{0}» прервал ответ: {1}", "„{0}“ hat die Antwort abgebrochen: {1}", "«{0}» interrumpió la respuesta: {1}", "« {0} » a interrompu la réponse : {1}"],
    "err_empty": ["“{0}” sent an empty answer — the free model may be busy. Press ↩ to retry or pick another model.", "«{0}» прислал пустой ответ — возможно, бесплатная модель перегружена. Нажмите ↩, чтобы повторить, или выберите другую модель.", "„{0}“ hat eine leere Antwort gesendet — das kostenlose Modell ist evtl. ausgelastet. ↩ zum Wiederholen oder anderes Modell wählen.", "«{0}» envió una respuesta vacía; puede que el modelo gratuito esté saturado. Pulsa ↩ para reintentar o elige otro modelo.", "« {0} » a renvoyé une réponse vide — le modèle gratuit est peut-être saturé. ↩ pour réessayer ou choisissez un autre modèle."],
    "gemini_section": ["Gemini (Google subscription)", "Gemini (подписка Google)", "Gemini (Google-Abo)", "Gemini (suscripción de Google)", "Gemini (abonnement Google)"],
    "note_gemini_auto": ["as in Gemini CLI", "как в Gemini CLI", "wie in Gemini CLI", "como en Gemini CLI", "comme dans Gemini CLI"],
    "err_no_gemini": ["Gemini CLI not found. Install it: `brew install gemini-cli` (or `npm install -g @google/gemini-cli`), then run `gemini` once and sign in with Google.", "Gemini CLI не найден. Установите его: `brew install gemini-cli` (или `npm install -g @google/gemini-cli`), затем один раз запустите `gemini` и войдите через Google.", "Gemini CLI nicht gefunden. Installieren: `brew install gemini-cli` (oder `npm install -g @google/gemini-cli`), dann einmal `gemini` starten und mit Google anmelden.", "No se encontró Gemini CLI. Instálalo: `brew install gemini-cli` (o `npm install -g @google/gemini-cli`), ejecuta `gemini` una vez e inicia sesión con Google.", "Gemini CLI introuvable. Installez-le : `brew install gemini-cli` (ou `npm install -g @google/gemini-cli`), puis lancez `gemini` une fois et connectez-vous avec Google."],
    "err_gemini_login": ["Gemini CLI is not signed in. Run `gemini` in a terminal and choose “Sign in with Google”.", "Gemini CLI не вошёл в аккаунт. Запустите `gemini` в терминале и выберите «Sign in with Google».", "Gemini CLI ist nicht angemeldet. Starten Sie `gemini` im Terminal und wählen Sie „Sign in with Google“.", "Gemini CLI no ha iniciado sesión. Ejecuta `gemini` en la terminal y elige «Sign in with Google».", "Gemini CLI n'est pas connecté. Lancez `gemini` dans un terminal et choisissez « Sign in with Google »."],
    "err_gemini": ["Gemini returned an error: {0}", "Gemini вернул ошибку: {0}", "Gemini meldete einen Fehler: {0}", "Gemini devolvió un error: {0}", "Gemini a renvoyé une erreur : {0}"],
]

private func format(_ key: String, _ args: [String]) -> String {
    var s = table[key]?[Lang.index] ?? key
    for (i, a) in args.enumerated() { s = s.replacingOccurrences(of: "{\(i)}", with: a) }
    return s
}

/// Every interface string, in the current language.
enum S {
    static var searchPlaceholder: String { format("search_placeholder", []) }
    static var followupPlaceholder: String { format("followup_placeholder", []) }
    static func askRow(_ a0: String) -> String { format("ask_row", [a0]) }
    static var application: String { format("application", []) }
    static var thinking: String { format("thinking", []) }
    static var hintStop: String { format("hint_stop", []) }
    static func hintDone(_ a0: String) -> String { format("hint_done", [a0]) }
    static var welcomeSubtitle: String { format("welcome_subtitle", []) }
    static var hotkeyHint: String { format("hotkey_hint", []) }
    static var authChecking: String { format("auth_checking", []) }
    static var authOk: String { format("auth_ok", []) }
    static var authSignedOut: String { format("auth_signed_out", []) }
    static var authMissing: String { format("auth_missing", []) }
    static var signIn: String { format("sign_in", []) }
    static var download: String { format("download", []) }
    static var model: String { format("model", []) }
    static var language: String { format("language", []) }
    static var languageSystem: String { format("language_system", []) }
    static var connectModel: String { format("connect_model", []) }
    static var deleteConnection: String { format("delete_connection", []) }
    static var launchAtLogin: String { format("launch_at_login", []) }
    static var showOnLaunch: String { format("show_on_launch", []) }
    static var openSearch: String { format("open_search", []) }
    static func menuOpenSearch(_ a0: String) -> String { format("menu_open_search", [a0]) }
    static var menuWindow: String { format("menu_window", []) }
    static var menuLaunchAtLogin: String { format("menu_launch_at_login", []) }
    static var menuQuit: String { format("menu_quit", []) }
    static var modelAuto: String { format("model_auto", []) }
    static var noteAuto: String { format("note_auto", []) }
    static var noteHaiku: String { format("note_haiku", []) }
    static var noteSonnet: String { format("note_sonnet", []) }
    static var noteOpus: String { format("note_opus", []) }
    static var noteFable: String { format("note_fable", []) }
    static var connections: String { format("connections", []) }
    static var formTitle: String { format("form_title", []) }
    static var formSubtitle: String { format("form_subtitle", []) }
    static var service: String { format("service", []) }
    static var name: String { format("name", []) }
    static var address: String { format("address", []) }
    static var apiKey: String { format("api_key", []) }
    static var keyStored: String { format("key_stored", []) }
    static var keyNotNeeded: String { format("key_not_needed", []) }
    static var cancel: String { format("cancel", []) }
    static var connect: String { format("connect", []) }
    static var presetOllama: String { format("preset_ollama", []) }
    static var presetLmstudio: String { format("preset_lmstudio", []) }
    static var presetOther: String { format("preset_other", []) }
    static func hintExample(_ a0: String) -> String { format("hint_example", [a0]) }
    static var hintLoadedModel: String { format("hint_loaded_model", []) }
    static var hintModelName: String { format("hint_model_name", []) }
    static var errNoClaude: String { format("err_no_claude", []) }
    static var errNotLoggedIn: String { format("err_not_logged_in", []) }
    static func errStart(_ a0: String) -> String { format("err_start", [a0]) }
    static var errClaude: String { format("err_claude", []) }
    static func errBadUrl(_ a0: String) -> String { format("err_bad_url", [a0]) }
    static func errKey(_ a0: String, _ a1: String, _ a2: String) -> String { format("err_key", [a0, a1, a2]) }
    static func err404(_ a0: String, _ a1: String) -> String { format("err_404", [a0, a1]) }
    static func err429(_ a0: String, _ a1: String) -> String { format("err_429", [a0, a1]) }
    static func errStatus(_ a0: String, _ a1: String, _ a2: String) -> String { format("err_status", [a0, a1, a2]) }
    static func errConnect(_ a0: String, _ a1: String) -> String { format("err_connect", [a0, a1]) }
    static var errLocalHint: String { format("err_local_hint", []) }
    static var loginDone: String { format("login_done", []) }
    static var askChatgpt: String { format("ask_chatgpt", []) }
    static var chatgptNote: String { format("chatgpt_note", []) }
    static var showChatgpt: String { format("show_chatgpt", []) }
    static func errStream(_ a0: String, _ a1: String) -> String { format("err_stream", [a0, a1]) }
    static func errEmpty(_ a0: String) -> String { format("err_empty", [a0]) }
    static var geminiSection: String { format("gemini_section", []) }
    static var noteGeminiAuto: String { format("note_gemini_auto", []) }
    static var errNoGemini: String { format("err_no_gemini", []) }
    static var errGeminiLogin: String { format("err_gemini_login", []) }
    static func errGemini(_ a0: String) -> String { format("err_gemini", [a0]) }
}
