#!/usr/bin/env python3
"""Generates Sources/Strings.swift and windows/Lumi/Strings.cs from strings.json.

Run after editing strings.json:  python3 strings/generate.py
"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
data = json.loads((Path(__file__).parent / "strings.json").read_text())
codes = [c for c, _ in data["languages"]]
names = [n for _, n in data["languages"]]
strings = data["strings"]
words = data["question_words"]


def camel(key, upper=False):
    parts = key.split("_")
    s = parts[0] + "".join(p.capitalize() for p in parts[1:])
    return s[0].upper() + s[1:] if upper else s


def arity(values):
    return max([int(n) + 1 for v in values for n in re.findall(r"\{(\d)\}", v)] or [0])


def lit(s):
    return json.dumps(s, ensure_ascii=False)


header = "// Generated by strings/generate.py from strings/strings.json — edit those, not this file.\n"

# Swift
sw = [header, "import Foundation\n", "/// Interface languages: code and native name, in table order.",
      "enum Lang {",
      f"    static let codes = [{', '.join(lit(c) for c in codes)}]",
      f"    static let names = [{', '.join(lit(n) for n in names)}]", "",
      "    /// The language in use: the one chosen in settings, else the system's, else English.",
      "    static var index: Int {",
      "        let chosen = UserDefaults.standard.string(forKey: \"language\") ?? \"\"",
      "        if let i = codes.firstIndex(of: chosen) { return i }",
      "        for preferred in Locale.preferredLanguages {",
      "            if let i = codes.firstIndex(of: String(preferred.prefix(2))) { return i }",
      "        }",
      "        return 0",
      "    }", "",
      "    /// Words that start a question in any interface language.",
      "    static let questionWords: Set<String> = [",
      "        " + ", ".join(lit(w) for ws in words.values() for w in ws),
      "    ]",
      "}", "",
      "private let table: [String: [String]] = ["]
for k, v in strings.items():
    sw.append(f"    {lit(k)}: [{', '.join(lit(x) for x in v)}],")
sw += ["]", "",
       "private func format(_ key: String, _ args: [String]) -> String {",
       "    var s = table[key]?[Lang.index] ?? key",
       "    for (i, a) in args.enumerated() { s = s.replacingOccurrences(of: \"{\\(i)}\", with: a) }",
       "    return s",
       "}", "",
       "/// Every interface string, in the current language.",
       "enum S {"]
for k, v in strings.items():
    n = arity(v)
    if n == 0:
        sw.append(f"    static var {camel(k)}: String {{ format({lit(k)}, []) }}")
    else:
        params = ", ".join(f"_ a{i}: String" for i in range(n))
        args = ", ".join(f"a{i}" for i in range(n))
        sw.append(f"    static func {camel(k)}({params}) -> String {{ format({lit(k)}, [{args}]) }}")
sw.append("}\n")
(root / "Sources" / "Strings.swift").write_text("\n".join(sw))

# C#
cs = [header, "using System.Collections.Generic;", "using System.Globalization;", "", "namespace Lumi;", "",
      "/// Interface languages: code and native name, in table order.",
      "public static class Lang", "{",
      f"    public static readonly string[] Codes = {{ {', '.join(lit(c) for c in codes)} }};",
      f"    public static readonly string[] Names = {{ {', '.join(lit(n) for n in names)} }};", "",
      "    /// The language in use: the one chosen in settings, else the system's, else English.",
      "    public static int Index",
      "    {",
      "        get",
      "        {",
      "            var i = System.Array.IndexOf(Codes, Settings.Shared.Language);",
      "            if (i >= 0) return i;",
      "            i = System.Array.IndexOf(Codes, CultureInfo.CurrentUICulture.TwoLetterISOLanguageName);",
      "            return i >= 0 ? i : 0;",
      "        }",
      "    }", "",
      "    /// Words that start a question in any interface language.",
      "    public static readonly HashSet<string> QuestionWords = new()",
      "    {",
      "        " + ", ".join(lit(w) for ws in words.values() for w in ws),
      "    };",
      "}", "",
      "/// Every interface string, in the current language.",
      "public static class S", "{",
      "    private static readonly Dictionary<string, string[]> Table = new()", "    {"]
for k, v in strings.items():
    cs.append(f"        [{lit(k)}] = new[] {{ {', '.join(lit(x) for x in v)} }},")
cs += ["    };", "",
       "    private static string F(string key, params string[] args)",
       "    {",
       "        var s = Table.TryGetValue(key, out var v) ? v[Lang.Index] : key;",
       "        for (var i = 0; i < args.Length; i++) s = s.Replace(\"{\" + i + \"}\", args[i]);",
       "        return s;",
       "    }", ""]
for k, v in strings.items():
    n = arity(v)
    if n == 0:
        cs.append(f"    public static string {camel(k, True)} => F({lit(k)});")
    else:
        params = ", ".join(f"string a{i}" for i in range(n))
        args = ", ".join(f"a{i}" for i in range(n))
        cs.append(f"    public static string {camel(k, True)}({params}) => F({lit(k)}, {args});")
cs.append("}\n")
(root / "windows" / "Lumi" / "Strings.cs").write_text("\n".join(cs))
print("generated", len(strings), "strings in", len(codes), "languages")
