"""Builds the Modelfiles from system.txt so both models share one prompt.
Run: python3 models/make.py, then ollama create lumi -f models/lumi.Modelfile"""
import json, pathlib

here = pathlib.Path(__file__).parent
system = (here / "system.txt").read_text().strip()

# A few short sample dialogs: small models copy examples better than they follow rules.
examples = [
    ("tell a client their order is a day late",
     "Hi! Unfortunately, your order will arrive one day later than planned. Sorry for the wait, and thank you for your patience."),
    ("напиши клиенту, что заказ задержится на день",
     "Здравствуйте! К сожалению, ваш заказ задержится на один день. Приносим извинения за неудобства и благодарим за терпение."),
    ("ты кто такой?",
     "Я Lumi, пиксельный призрак из приложения Lumi. Нажми горячую клавишу в любом окне, спроси что угодно, и я отвечу прямо здесь, без интернета."),
    ("ответь вежливо руководителю, что задержусь на созвон",
     "Добрый день! Задерживаюсь на пару минут, скоро подключусь. Извините за ожидание."),
    ("Word не сохраняет файл, пишет «отказано в доступе»",
     "Скорее всего, у Word нет прав на эту папку или файл открыт в другой программе.\n\n1. Закройте другие окна с этим файлом.\n2. Сохраните через «Сохранить как» в «Документы» или на рабочий стол.\n3. Если получилось, дело в правах на исходную папку."),
]

# name: (title, about, base model, download size in GB, memory it wants in GB, temperature)
models = {
    "lumi-mini": ("Lumi Mini", "the lightest ghost for older laptops (8 GB of memory)", "gemma4:e2b-it-q4_K_M", 4.6, 8, 0.4),
    "lumi": ("Lumi", "the ghost's own model for most laptops (12-16 GB of memory)", "gemma4:e4b-it-q4_K_M", 6.6, 12, 0.4),
    "lumi-pro": ("Lumi Pro", "the smartest ghost for powerful computers (32 GB of memory or more)", "qwen3.6:35b-a3b-q4_K_M", 23.9, 32, 0.6),
}

for name, (title, about, base, size, memory, temp) in models.items():
    lines = [f"# {title} — {about}.",
             "# Generated by models/make.py from system.txt; edit those, not this file.",
             f"# Build: ollama create {name} -f models/{name}.Modelfile",
             f"FROM {base}", f"PARAMETER temperature {temp}", "PARAMETER num_ctx 8192",
             f'SYSTEM """\n{system}\n"""']
    for q, a in examples:
        lines += [f"MESSAGE user {json.dumps(q, ensure_ascii=False)}",
                  f'MESSAGE assistant """{a}"""']
    (here / f"{name}.Modelfile").write_text("\n".join(lines) + "\n")
    print("wrote", name)

# The same recipes for the apps, which build the models on the user's computer through Ollama's API.
def swift(text):
    return json.dumps(text, ensure_ascii=False)

recipes = ",\n".join(
    f'        LumiRecipe(name: "{n}", title: "{t}", base: "{b}", sizeGB: {s}, memoryGB: {m}, temperature: {tp})'
    for n, (t, _, b, s, m, tp) in models.items())
pairs = ",\n".join(f"        ({swift(q)}, {swift(a)})" for q, a in examples)
(here.parent / "Sources/LumiModels.swift").write_text(f"""// Generated by models/make.py from models/system.txt; edit those, not this file.

struct LumiRecipe: Hashable {{
    let name, title, base: String
    let sizeGB: Double
    let memoryGB: Int
    let temperature: Double
}}

enum LumiModels {{
    static let all = [
{recipes},
    ]

    static let system = {swift(system)}

    static let examples: [(question: String, answer: String)] = [
{pairs},
    ]
}}
""")

recipes = ",\n".join(
    f'        new("{n}", "{t}", "{b}", {s}, {m}, {tp})'
    for n, (t, _, b, s, m, tp) in models.items())
pairs = ",\n".join(f"        ({swift(q)}, {swift(a)})" for q, a in examples)
(here.parent / "windows/Lumi/LumiModels.cs").write_text(f"""// Generated by models/make.py from models/system.txt; edit those, not this file.
namespace Lumi;

public sealed record LumiRecipe(string Name, string Title, string Base, double SizeGB, int MemoryGB, double Temperature);

public static class LumiModels
{{
    public static readonly LumiRecipe[] All =
    [
{recipes},
    ];

    public const string System = {swift(system)};

    public static readonly (string Question, string Answer)[] Examples =
    [
{pairs},
    ];
}}
""")
print("wrote app recipes")
