"""Builds the Modelfiles from system.txt so both models share one prompt.
Run: python3 models/make.py, then ollama create lumi -f models/lumi.Modelfile"""
import json, pathlib

here = pathlib.Path(__file__).parent
system = (here / "system.txt").read_text().strip()

# A few short sample dialogs: small models copy examples better than they follow rules.
examples = [
    ("who are you?",
     "I'm Lumi, a little pixel ghost living in the Lumi app on your Mac or PC. Press the hotkey from any window, ask anything, and I answer right here, offline."),
    ("напиши клиенту, что заказ задержится на день",
     "Здравствуйте! К сожалению, ваш заказ задержится на один день. Приносим извинения за неудобства и благодарим за терпение."),
    ("Word не сохраняет файл, пишет «отказано в доступе»",
     "Скорее всего, у Word нет прав на эту папку или файл открыт в другой программе.\n\n1. Закройте другие окна с этим файлом.\n2. Сохраните через «Сохранить как» в «Документы» или на рабочий стол.\n3. Если получилось, дело в правах на исходную папку."),
]

models = {
    "lumi": ("the ghost's own model for most laptops (16 GB of memory or more)", "qwen3.5:9b-q4_K_M", 0.4),
    "lumi-pro": ("the smartest ghost for powerful computers (32 GB of memory or more)", "qwen3.6:35b-a3b-q4_K_M", 0.6),
}

for name, (about, base, temp) in models.items():
    lines = [f"# {name.capitalize() if name == 'lumi' else 'Lumi Pro'} — {about}.",
             "# Generated by models/make.py from system.txt; edit those, not this file.",
             f"# Build: ollama create {name} -f models/{name}.Modelfile",
             f"FROM {base}", f"PARAMETER temperature {temp}", "PARAMETER num_ctx 8192",
             f'SYSTEM """\n{system}\n"""']
    for q, a in examples:
        lines += [f"MESSAGE user {json.dumps(q, ensure_ascii=False)}",
                  f'MESSAGE assistant """{a}"""']
    (here / f"{name}.Modelfile").write_text("\n".join(lines) + "\n")
    print("wrote", name)
